INSERT INTO products (id,name,price,description,img,imageid,manufact,stock) VALUES
	 (7,'Bugatti Centodieci',960000000,'The Bugatti Centodieci is a limited production mid-engine sports car produced by French automotive manufacturer Bugatti. The car is a homage to the Bugatti EB 110 and a celebration 110th birthday.','https://github.com/ScythK0TH/Project_HC/blob/main/src/lib/file/images/Image_B1.jpg?raw=true',2,'Bugatti',99),
	 (9,'Porsche 911 GT3 RS',25900000,'4.0 liter Boxer 6-cylinder gasoline engine, without compressed air. Providing a maximum power of 525 horsepower (PS), paired with a 7-speed PDK automatic transmission','https://github.com/ScythK0TH/Project_HC/blob/main/src/lib/file/images/Image_P2.jpg?raw=true',1,'Porsche',96),
	 (10,'Porsche Unveils 963',115000000,'Thomas Laudenbach, Vice President Motorsport, said: “After completing 7,889 kilometers of testing in the first half of 2022, we are on a very good path, but there is still a lot of work to be','https://github.com/ScythK0TH/Project_HC/blob/main/src/lib/file/images/Image_P0.jpg?raw=true',2,'Porsche',94),
	 (12,'Bugatti Divo ',195000000,'The power comes in a 8.0 liter W16 with 4 turbos, producing a maximum power of 1,500 horsepower at 6,700 rpm, a maximum torque of 1,600 newton-meters from 2,000-6,000 rpm, and an acceleration','https://github.com/ScythK0TH/Project_HC/blob/main/src/lib/file/images/Image_B0.jpg?raw=true',3,'Bugatti',100),
	 (6,'Bugatti Bolide',594000000,'The Bugatti Bolide is a track-only sports car developed by Bugatti Engineering GmbH in Wolfsburg, Germany and manufactured in Molsheim, by French automobile manufacturer Bugatti Automobiles S.A.S.','https://github.com/ScythK0TH/Project_HC/blob/main/src/lib/file/images/Image_B3.png?raw=true',1,'Bugatti',100),
	 (5,'Bugatti Chiron',106000000,'The heart is an 8-liter W16 engine with 4 turbos that have been increased to 200 rpm from the normal Chiron to 6,900 rpm, maximum torque of 1,600 newton-meters at 2,000-6,000 rpm, acceleratio','https://github.com/ScythK0TH/Project_HC/blob/main/src/lib/file/images/Image_B2.jpg?raw=true',0,'Bugatti',92),
	 (8,'Porsche 918',128000000,'It uses a 4.6 liter V8 engine producing 608 horsepower (453 kW) with two electric motors producing an additional 279 horsepower (208 kW), for a total of 887 horsepower (661 kW). The car can r','https://github.com/ScythK0TH/Project_HC/blob/main/src/lib/file/images/Image_P3.jpg?raw=true',0,'Porsche',85),
	 (3,'Ferrari SP-8',720260000,'The twin-turbo 3.9-liter V8 engine mounted behind the seats produces 710 horsepower and 568 pound-feet of torque in an engine claimed to propel the car to a sub-3.0-second time to 60 mph.','https://github.com/ScythK0TH/Project_HC/blob/main/src/lib/file/images/Image_F1.avif?raw=true',2,'Ferrari',52),
	 (11,'Porsche 718 Boxster',9190000,'Gasoline engine, 6 cylinders, DOHC, 24 valves, size 4.0 liters, 3,996 cc, cylinder x stroke length: 102.0 x 81.5 mm, compression power 13.3: 1 with Variocam variable valve system on both the ','https://github.com/ScythK0TH/Project_HC/blob/main/src/lib/file/images/Image_P1.jpg?raw=true',3,'Porsche',52),
	 (1,'Ferrari SP48',40500000,'In terms of power, it still uses a V8 Twin Turbo gasoline engine with a maximum power of 710 horsepower and a maximum torque of 770 Newton-meters. It can accelerate from 0-100 km/hr in 2.9 se','https://github.com/ScythK0TH/Project_HC/blob/main/src/lib/file/images/Image_F2.jpg?raw=true',0,'Ferrari',35);
INSERT INTO products (id,name,price,description,img,imageid,manufact,stock) VALUES
	 (2,'Ferrari ROMA',21230000,'Roma''s lengthy hood and mounted near the middle of the car is a turbocharged 3.9-liter V-8 that makes 612 horsepower and 561 pound-feet of torque. It pairs with an eight-speed dual-clutch aut','https://github.com/ScythK0TH/Project_HC/blob/main/src/lib/file/images/Image_F3.jpg?raw=true',1,'Ferrari',64),
	 (4,'Ferrari LaFerrari',347000000,'V12 gasoline engine, size 6.5 liters, 6,496 cc. Cylinder x Stroke length: 94.0 x 78.0 mm. Compression ratio 13.6 : 1. Maximum power 800 horsepower at 8,500 rpm. Maximum torque 718 Newton mete','https://github.com/ScythK0TH/Project_HC/blob/main/src/lib/file/images/Image_F0.jpg?raw=true',3,'Ferrari',92);
